### PR TITLE
Changes required to point at main branch

### PR DESCRIPTION
**Pull request by catlee**

### CODE REVIEW

**Review by macournoyer — APPROVED** [review]
❤️

**Comment by charlespwd** [comment]
Do you know if we can somehow have GitHub redirects for the master->main after a rename? This would still require users to upgrade theme-check in order to have the links working :/

**Comment by macournoyer** [comment]
Apparently, it redirects to the default branch: https://github.com/github/renaming#whats-already-changed

**Comment by catlee** [comment]
image

**Comment by charlespwd** [comment]
Woo! That's perfect. Should try it though. I got burned when trying to do this for theme-check-vscode. The Shopify logo link stopped working.

**Pull request merged**
